### ISSUE TITLE
Move image away from alpine base

### ISSUE THREAD

**Issue by cmccandless** [exercism/python-representer#3]
See the following for more information:
- [Alpine makes Python Docker builds 50× slower, and images 2× larger](https://pythonspeed.com/articles/alpine-docker-python/)
- [The best Docker base image for your Python application (January 2020)](https://pythonspeed.com/articles/base-image-python-docker-images/)

**Comment by BethanyG** [comment]
I believe this was "fixed" in PR #6, or thereabouts.  Current dockerfile uses `slim`.  Closing.
